# Generated by Django 5.0.1 on 2024-02-05 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('requirements', models.CharField(blank=True, max_length=10000, null=True)),
                ('details', models.CharField(blank=True, max_length=10000, null=True)),
                ('skills', models.CharField(blank=True, max_length=10000, null=True)),
                ('job_type', models.CharField(choices=[('fulltime', 'fulltime'), ('parttime', 'parttime')], max_length=200, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not seen', 'not seen'), ('seen', 'seen'), ('refused', 'refused'), ('accepted', 'accepted')], default='not seen', max_length=8)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'unique_together': {('applicant', 'job')},
            },
        ),
    ]
