# Generated by Django 5.0.1 on 2024-01-27 09:27

import accounts.validators.facebookLink
import accounts.validators.gender
import accounts.validators.instagramLink
import accounts.validators.phone_number
import accounts.validators.telegramLink
import accounts.validators.twitterLink
import accounts.validators.username
import accounts.validators.whatsappLink
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True, validators=[accounts.validators.username.usernameValidator])),
                ('password', models.CharField(max_length=5000)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, validators=[accounts.validators.gender.genderValidator])),
                ('date_of_birth', models.DateField()),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('first_login', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[accounts.validators.phone_number.phoneNumberEgyptValidator])),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.whatsappLink.whastappLinkEgyptValidator])),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.telegramLink.telegramLinkValidator])),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.facebookLink.facebookLinkValidator])),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.instagramLink.instagramLinkValidator])),
                ('twitter', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.twitterLink.twitterLinkValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.contact'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
