# Generated by Django 5.0.1 on 2024-02-01 02:44

import accounts.validators.date_of_birth
import accounts.validators.facebookLink
import accounts.validators.gender
import accounts.validators.instagramLink
import accounts.validators.phone_number
import accounts.validators.telegramLink
import accounts.validators.twitterLink
import accounts.validators.whatsappLink
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[accounts.validators.phone_number.phoneNumberEgyptValidator])),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.whatsappLink.whastappLinkEgyptValidator])),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.telegramLink.telegramLinkValidator])),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.facebookLink.facebookLinkValidator])),
                ('instagram', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.instagramLink.instagramLinkValidator])),
                ('twitter', models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.twitterLink.twitterLinkValidator])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=5000)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1, validators=[accounts.validators.gender.genderValidator])),
                ('date_of_birth', models.DateField(validators=[accounts.validators.date_of_birth.dateOfBirthValidator])),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='account_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='account_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.contact')),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(default=0)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
