# Generated by Django 5.0.1 on 2024-02-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='end_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_at',
            field=models.DateField(),
        ),
    ]
