# Generated by Django 5.0.1 on 2024-02-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_vacation_end_at_alter_vacation_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='status',
            field=models.CharField(choices=[('not seen', 'not seen'), ('seen', 'seen'), ('refused', 'refused'), ('accepted', 'accepted')], default='not seen', max_length=8),
        ),
    ]
